package crawl;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * CrawlOneBugService service = new CrawlOneBugService();
 * CrawlOneBugDelegate portType = service.getCrawlOneBugPort();
 * portType.crawlFromOneBug(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "CrawlOneBugService", targetNamespace = "http://bugtrackingsystem.citrite.net", wsdlLocation = "http://127.0.0.1:8888/CrawlOneBugWebService/CrawlOneBugPort?wsdl")
public class CrawlOneBugService extends Service {

	private final static URL CRAWLONEBUGSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(crawl.CrawlOneBugService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = crawl.CrawlOneBugService.class.getResource(".");
			url = new URL(baseUrl,
					"http://127.0.0.1:8888/CrawlOneBugWebService/CrawlOneBugPort?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:8888/CrawlOneBugWebService/CrawlOneBugPort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		CRAWLONEBUGSERVICE_WSDL_LOCATION = url;
	}

	public CrawlOneBugService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public CrawlOneBugService() {
		super(CRAWLONEBUGSERVICE_WSDL_LOCATION, new QName(
				"http://bugtrackingsystem.citrite.net", "CrawlOneBugService"));
	}

	/**
	 * 
	 * @return returns CrawlOneBugDelegate
	 */
	@WebEndpoint(name = "CrawlOneBugPort")
	public CrawlOneBugDelegate getCrawlOneBugPort() {
		return super.getPort(new QName("http://bugtrackingsystem.citrite.net",
				"CrawlOneBugPort"), CrawlOneBugDelegate.class);
	}

}
