package crawl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "CrawlOneBugDelegate", targetNamespace = "http://bugtrackingsystem.citrite.net")
public interface CrawlOneBugDelegate {

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "crawlFromOneBug", targetNamespace = "http://bugtrackingsystem.citrite.net", className = "crawl.CrawlFromOneBug")
	@ResponseWrapper(localName = "crawlFromOneBugResponse", targetNamespace = "http://bugtrackingsystem.citrite.net", className = "crawl.CrawlFromOneBugResponse")
	public String crawlFromOneBug(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

}
